
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return const FirebaseOptions(
      apiKey: 'AIzaSyCe0_3d-3kXyQ5u0iwY70nrjgE8T7Jh504',
      appId: '1:683707077317:android:3bf113bd9106b238d9d6ac',
      messagingSenderId: '683707077317',
      projectId: 'login-757c3',
      storageBucket: 'login-757c3.firebasestorage.app',
    );
  }
}


// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       // return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         // return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//               'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//               'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//               'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   // static const FirebaseOptions web = FirebaseOptions(
//   //   apiKey: 'AIzaSyB0ktXNm85YBDa9w6xS3ObhjnGL76ZkR8Y',
//   //   appId: '1:814947343722:web:883b04c90b405c75631913',
//   //   messagingSenderId: '814947343722',
//   //   projectId: 'chatingapp-db265',
//   //   authDomain: 'chatingapp-db265.firebaseapp.com',
//   //   databaseURL: 'https://chatingapp-db265-default-rtdb.firebaseio.com',
//   //   storageBucket: 'chatingapp-db265.appspot.com',
//   //   measurementId: 'G-MKVQG05PHJ',
//   // );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCe0_3d-3kXyQ5u0iwY70nrjgE8T7Jh504',
//     appId: '1:683707077317:android:3bf113bd9106b238d9d6ac',
//     messagingSenderId: '814947343722',
//     projectId: 'login-757c3',
//     // databaseURL: 'https://chatingapp-db265-default-rtdb.firebaseio.com',
//     storageBucket: 'login-757c3.firebasestorage.app',
//   );
//
//   // static const FirebaseOptions ios = FirebaseOptions(
//   //   apiKey: 'AIzaSyD3KhlmMUDFbGjhl-uCTUX6XxZyLN-ADLk',
//   //   appId: '1:683707077317:android:3bf113bd9106b238d9d6ac',
//   //   messagingSenderId: '814947343722',
//   //   projectId: 'chatingapp-db265',
//   //   databaseURL: 'https://chatingapp-db265-default-rtdb.firebaseio.com',
//   //   storageBucket: 'chatingapp-db265.appspot.com',
//   //   iosClientId: '814947343722-t2apeqc78t9elmtpuc52d3quul91ij3b.apps.googleusercontent.com',
//   //   iosBundleId: 'com.example.chatingapp',
//   // );
//
// }